### ISSUE TITLE
 Not following CHIP-0007 Standard

### ISSUE THREAD

**Issue by green-app-io** [mintgarden-io/mintgarden-studio#3]
#### What did I do

While creating NFT, it was found that json file with metadata was not created correctly. Instead of "trait_type" in attributes, use "name"

Link to NFT https://www.spacescan.io/xch/nft/nft14lrt78g96gq87ahgjlk67d5tlz6u0alkgccg750ru6zhnd4vv7cset3kwz

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- mintgarden-studio version (or commit hash), e.g. v1.0.0

#### More detail

<img width="553" alt="image" src="https://user-images.githubusercontent.com/101601715/185412220-8d20823a-5d10-44ce-8aa5-3332136b49d5.png">

**Comment by greimela** [comment]
Thank you for the report, this has been fixed in v0.1.6.
